git:
  depth: 10

sudo: false

cache:
  directories:
    - "node_modules"

language: node_js

node_js:
  - "8.9.4"

before_install:
  - npm i -g npm@6.1.0

before_script:
  - npm install

script: npm run test